### PR TITLE
feat(common): add controller.type of cronjob

### PR DESCRIPTION
**Pull request by loeken**
### Description of the change

I started to use your library for most of my apps ( great job on this library btw! ). I have to run some of my applications as cronjobs, so i added a controller.type of deployment to generate a CronJob object. I tested the generated output to adhere to snyk's default rules.

#### Removed

no features removed

### Benefits

users will be able to run cronjobs of certain images to achive certain things

### Applicable issues

- fixes #

## Checklist

- [X] Title of the PR conforms to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
- [X] Scope of the of the PR title contains the chart name.
- [X] Chart version in `Chart.yaml` has been bumped according to [Semantic Versioning](https://semver.org/).
- [X] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [X] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Comment by loeken** [comment]
I hope i understood the error of your failing test correctly and pushed the changes to correct
```
Error: Error: The head commit for this pull_request event is not ahead of the base commit.
```

**Comment by loeken** [comment]
any other changes required?

**Comment by bjw-s** [comment]
> any other changes required?

Thanks for the kind words and for raising this PR! It took me a bit longer to get to due to $life stuff but I'm going to go over it today and try to get this merged in to the `development` branch.

**Review by bjw-s — APPROVED** [review]
Changes look good to me! Going to merge into development now, will add some unit tests etc there

**Pull request merged**
