### PR TITLE
ci: add workflow to create oci artifact

### PR DESCRIPTION
**Pull request by coolguy1771**
Signed-off-by: Tyler Witlin <tyler@codezero.io>

**Description of the change**

This PR add a workflow to create and push charts to GHCR as an OCI artifact.

**Benefits**

Flux users can now use this repository using the new OCI artifacts.

**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [x] Title of the PR conforms to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
- [x] Scope of the of the PR title contains the chart name.
- [ ] Chart version in `Chart.yaml` has been bumped according to [Semantic Versioning](https://semver.org/).
- [ ] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [ ] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Comment by andrasmaroy** [comment]
I'd also love to use this with flux, is there something that we can contribute with to get this merged?

**Comment by coolguy1771** [comment]
> I'd also love to use this with flux, is there something that we can contribute with to get this merged?

I think it just needs to be tested

**Comment by bjw-s** [comment]
TBH I didn't think many folks would want this... I'll see if I can get it implemented somewhere in the coming week 👍

**Comment by tamcore** [comment]
This would be very useful, as it's easier to cache an OCI chart with Harbor's pull-through cache, than a standard helm chart :)

**Comment by bjw-s** [comment]
I've merged it as-is and will try and tweak in the `development` branch. Thanks for the PR @coolguy1771!

**Comment by bjw-s** [comment]
https://github.com/bjw-s/helm-charts/pkgs/container/app-template

`app-template` is being published to GHCR as an OCI artifact now :)

**Pull request merged**
