### PR TITLE
Remove references to the legacy additionalContainers value

### PR DESCRIPTION
**Pull request by fernandodeperto**
### Description of the change
The `additionalContainers` value is mentioned in a few places (documentation and code) as legacy and it's confusing. The new value (`sidecars`) is in place and can be used.

#### Removed
* Removed support for the `.Values.additionalContainers` key in values

### Applicable issues

- fixes #

## Checklist

- [ ] Title of the PR conforms to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
- [ ] Scope of the of the PR title contains the chart name.
- [ ] Chart version in `Chart.yaml` has been bumped according to [Semantic Versioning](https://semver.org/).
- [ ] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [ ] Variables have been documented in the `values.yaml` file.

### CODE REVIEW

**Comment by bjw-s** [comment]
Thank you for taking the time to make this PR! Given that the big `rewrite` branch is almost complete, I would suggest that you hold off on doing any work on this for now. I'm afraid otherwise that you'd be doing a lot of work that might get negated by the rewrite. I will of course take a look through the updated codebase to see if I can find any remnants.

**Comment by fernandodeperto** [comment]
Thank you for the quick response also. Would you prefer that I ported this change to the rewrite branch, or just park it for now until you've merged?

**Comment by bjw-s** [comment]
I think it would be best to park it for a little bit. The new release shouldn't be more than a week or two away now. Mostly some tidying up and documentation updates that I still need to do

**Comment by bjw-s** [comment]
I think we can close this now that v2 has been released. Still, thank you very much again for the PR that you created!

**Pull request closed without merging**
